# Generated by Django 3.2 on 2021-05-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=70)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('nodeType', models.CharField(choices=[('S', 'Station'), ('A', 'Airport')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RESTApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseUrl', models.CharField(max_length=50)),
                ('APIKey', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('PartToaddToBaseUrl', models.CharField(max_length=200)),
                ('funcToExtractDataFromJsonName', models.CharField(max_length=100)),
                ('ParamsOrDataDictStructure', models.JSONField()),
                ('typeRequests', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], max_length=5)),
                ('headers', models.JSONField(blank=True)),
                ('RApi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restapi')),
            ],
        ),
    ]
