# Generated by Django 3.2 on 2021-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('PartToaddToBaseUrl', models.CharField(max_length=200)),
                ('funcToExtractDataFromJsonName', models.CharField(max_length=100)),
                ('ParamsOrDataDictStructure', models.JSONField()),
                ('headers', models.JSONField()),
                ('typeRequests', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], max_length=5)),
            ],
        ),
    ]
