# Generated by Django 3.2 on 2021-05-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField()),
                ('arrivalDate', models.DateField()),
                ('duration', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='skyscannerTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlPago', models.CharField(max_length=1500)),
                ('AirlineName', models.CharField(max_length=50)),
                ('AirlineUrlImage', models.CharField(max_length=50)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='busOrTrainTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('T', 'Train'), ('B', 'Bus')], max_length=5)),
                ('arrivalNode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrivalNode', to='app.node')),
                ('departureNode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departureNode', to='app.node')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
        migrations.CreateModel(
            name='blablaTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=150)),
                ('departureCity', models.CharField(max_length=30)),
                ('departureAddress', models.CharField(max_length=30)),
                ('departureLatitude', models.FloatField()),
                ('departureLongitude', models.FloatField()),
                ('arrivalCity', models.CharField(max_length=30)),
                ('arrivalAddress', models.CharField(max_length=30)),
                ('arrivalLatitude', models.FloatField()),
                ('arrivalLongitude', models.FloatField()),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
            ],
        ),
    ]
