# Generated by Django 3.2 on 2021-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
