# Generated by Django 3.2 on 2021-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
