# Generated by Django 3.2 on 2021-04-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESTApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseUrl', models.CharField(max_length=50)),
                ('APIKey', models.CharField(max_length=50)),
                ('Requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.request')),
            ],
        ),
    ]
