# Generated by Django 3.2.3 on 2021-07-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_node_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ParamsOrDataDictStructure',
            field=models.CharField(max_length=1000),
        ),
    ]
