# Generated by Django 3.2 on 2021-05-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_node_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
