# Generated by Django 3.2 on 2021-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='headers',
            field=models.JSONField(null=True),
        ),
    ]
