# Generated by Django 3.2 on 2021-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blablatrip_busortraintrip_skyscannertrip_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrivalDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departureDate',
            field=models.DateTimeField(),
        ),
    ]
