# Generated by Django 3.2 on 2021-05-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_request_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='province',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
