# Generated by Django 3.2 on 2021-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210512_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blablatrip',
            name='link',
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skyscannertrip',
            name='urlPago',
            field=models.URLField(max_length=1500),
        ),
    ]
