# Generated by Django 3.2.3 on 2021-07-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_request_paramsordatadictstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blablatrip',
            name='arrivalAddress',
            field=models.CharField(max_length=200),
        ),
    ]
