# Generated by Django 3.2.3 on 2021-07-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blablatrip_arrivaladdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skyscannertrip',
            name='airlineUrlImage',
            field=models.CharField(max_length=150),
        ),
    ]
