# Generated by Django 3.2 on 2021-05-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210512_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skyscannertrip',
            old_name='urlPago',
            new_name='urlPay',
        ),
    ]
