# Generated by Django 3.2.3 on 2021-07-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_skyscannertrip_airlineurlimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blablatrip',
            name='arrivalCity',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blablatrip',
            name='departureAddress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blablatrip',
            name='departureCity',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='restapi',
            name='BaseUrl',
            field=models.CharField(max_length=150),
        ),
    ]
