# Generated by Django 3.2 on 2021-05-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210512_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busortraintrip',
            name='arrivalNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivalNode', to='app.node'),
        ),
        migrations.AlterField(
            model_name='busortraintrip',
            name='departureNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departureNode', to='app.node'),
        ),
    ]
