# Generated by Django 3.2 on 2021-05-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210517_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busortraintrip',
            name='arrivalNode',
        ),
        migrations.RemoveField(
            model_name='busortraintrip',
            name='departureNode',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrivalNode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivalNode', to='app.node'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departureNode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departureNode', to='app.node'),
        ),
    ]
