# Generated by Django 3.2.3 on 2021-05-29 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210518_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blablatrip',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blablaTrip', to='app.trip'),
        ),
        migrations.AlterField(
            model_name='busortraintrip',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busOrTrainTrip', to='app.trip'),
        ),
        migrations.AlterField(
            model_name='skyscannertrip',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skyscannerTrip', to='app.trip'),
        ),
    ]
